# Generated by Django 4.2.4 on 2023-08-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ContactNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
